### ISSUE TITLE
tests warning on ref

### ISSUE THREAD

**Issue by trim21** [bangumi/frontend#228]
https://github.com/bangumi/frontend/pull/225

多了个warning，我不太熟悉react，这里不知道怎么修

```text
 PASS  packages/website/src/pages/login/index.spec.tsx
  ● Console

    console.error
      Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

      Check the render method of `Login`.
          at onVerify (C:\Users\Trim21\proj\bangumi\frontend\packages\website\src\pages\login\index.spec.tsx:11:74)
          at div
          at div
          at div
          at useState (C:\Users\Trim21\proj\bangumi\frontend\packages\website\src\pages\login\index.tsx:16:51)
          at children (C:\Users\Trim21\proj\bangumi\frontend\packages\website\src\hooks\use-user.tsx:45:61)

      36 |   mockedUseNavigate.mockReturnValue(mockedNavigate);
      37 |
    > 38 |   const { getByPlaceholderText, getByText } = render(
         |                                                     ^
      39 |     <UserProvider>
      40 |       <LoginPage />
      41 |     </UserProvider>,
```

_Originally posted by @trim21 in https://github.com/bangumi/frontend/issues/225#issuecomment-1331079097_

**Comment by trim21** [comment]
应该是`jest.mock('@hcaptcha/react-hcaptcha'`的问题，这里的组件没法添加ref，会导致另一个问题

   ReferenceError: C:\Users\Trim21\proj\bangumi\frontend\packages\website\src\pages\login\index.spec.tsx: The module factory of `jest.mock()` is not allowed to reference any out-of-scope variables.
    Invalid variable access: React
